### PR TITLE
added assets for electro titan, battle drill & recall spell

### LINKED ISSUE #5: add new troops and townhall
recently new troop electro titan and town hall 15 has been released.

### PR DESCRIPTION
**Pull request by devsargam**

### CODE REVIEW

**Comment by devsargam** [comment]
resolves #5 but townhall is not added yet.

**Comment by bsantosh909** [comment]
@devsargam We also have new spell, can you add icon for that as well? 🙏

**Comment by devsargam** [comment]
@TheLearneer sure

**Review by bsantosh909 — APPROVED** [review]

**Comment by bsantosh909** [comment]
@devsargam Thank you for helping out with these. Really appreciate it 🙏

**Pull request merged**
